### ISSUE TITLE
Videos menu loads when launching a game from widget.

### ISSUE THREAD

**Issue by Tazzlyn** [zach-morris/plugin.program.iagl#118]
If I have an IAGL game list as the directory for a widget, whenever I select one of them, it loads the videos menu before launching the game. Here's a video of the behavior.

https://streamable.com/zziyd

It happens with any skin I use, currently using Arctic Zephyr 2. Also, it doesn't do this when I launch content from other add-ons in a widget, so I figure it's something to do with IAGL. I've tried changing certain settings, but can't get the behavior to change. All in all, it's a really minor issue and IAGL in Kodi is just the greatest thing. Thanks!

**Comment by zach-morris** [comment]
OK, i think i found where this is happening.  With widgets, after the game successfully launches, the addon closes the info page screen.  If it's a widget, then I command Kodi to go back to the home screen, but Kodi in this case says:
```
INFO: Activate of window '10000' refused because there are active modal dialogs
```
It seems like some sort of race condition, I'll see if I can figure out how to fix it.

**Comment by drinfernoo** [comment]
@zach-morris It also happens when information *isn't* the default action.

**Comment by zach-morris** [comment]
I think it's fixed now.  If possible, please give the latest master in git a try

**Comment by Tazzlyn** [comment]
It still seems to be happening. I may have installed the wrong update, but uninstalling and reinstalling the latest master from .zip still has the same issue for me. Also tried updating through the repo.

**Comment by zach-morris** [comment]
I've updated the addon to 2.1.3 and I believe / hope this is fixed.  If you still see a problem please let me know.

**Comment by Tazzlyn** [comment]
I updated to 2.1.3 and updated Kodi and restarted everything and the behavior is still the same.

**Comment by zach-morris** [comment]
OK I missed one minor change with the last update, so this is slightly better.
https://streamable.com/6wsjx

I've updated it to go back to the home screen after the download and launch is called, so at worst, you'll see it in the background when it's downloading and then it will flash back to the home screen.

**Comment by Tazzlyn** [comment]
Something I should have mentioned is that I'm using an external launcher - RetroArch.

The new update works perfectly, when it's launched using an emulator for Kodi, but it behaves the same when using Retroarch.

Here I have one widget set up to use Kodi's Stella 2014 for Atari 2600, and the other widget set up to use RetroArch.

https://streamable.com/1craq

**Comment by zach-morris** [comment]
Doh, forgot external, ok i'll update that as well

**Comment by Tazzlyn** [comment]
That's perfect! Thank you so much!

**Comment by zach-morris** [comment]
Closing since the fix is in 2.1.4
